### EDA (Exploratory Data Analysis) with Pandas
- Some methods that we can run on dataframes
- Basic Inspection methods:
    - `df.head()` - give you the first 5 elements
        - an argument of 10 will give you first 10 elements
    - df.tail() - last 5 but argument can change the number
    - `df.sample()` - one random entry from the dataset
        - an argument can change that number too 
        - we use this to check how our datasets look like inside
- Basic attributes of a dataframe:
    - `df.shape` - tells you the shape of the df --- how many elements along how many axes
    - df.size - how many elements there are
    - df.ndim - will tell you the number of axes there are in the df --- generally just 2
    - `df.dtypes` - will tell you the data type of each column



- Methods for Statistical information as well:
    - `df.info()` - general information about the df
        - how many records, how many columns, what is the data type of those columns
        - also gives an idea of if there are any missing values in data
    - `df.describe()` - gives us the statistical measurements of the columns like count, mean, min, max, std, percentiles 
-

In [2]:
import pandas as pd

df = pd.read_csv("wc_2026.csv")
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [ ]:
df.head()
df.tail()
df.sample(5)

df.shape
df.size 
df.dtypes

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     object
 1   stage                104 non-null    object
 2   team1                104 non-null    object
 3   team2                104 non-null    object
 4   venue                104 non-null    object
 5   city                 104 non-null    object
 6   country              104 non-null    object
 7   date                 104 non-null    object
 8   kickoff_et           104 non-null    object
 9   team1_confederation  72 non-null     object
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     object
 12  team2_confederation  72 non-null     object
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     object
dtypes: float64(2), object(13)
memory usage: 12.3+ KB

- object is used for mixed data type
    - same as numpy array if you mixed data types
    -

Exercise:
- Please go to Kaggle
- Download this dataset: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially the EDA that we learnt about in today's class on it

## Filtering
- filter rows and columns
- uses boolean indexing
- keep only the rows you care about
- 
- df[condition] # or mask

In [29]:
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [ ]:
# Question 1: show me the matches played in Canada
mask = df["country"] == 'Canada'
df[mask]


df[df['country'] == 'Canada']


# Question 2: Give me the data for the matches in which team1_fifa_rank was <= 10 
df[df['team1_fifa_rank'] <= 10]

# Question 3: Give me the data for the matches in which both teams were < 10 fifa rank
df[(df['team1_fifa_rank'] < 10) & (df['team2_fifa_rank'] < 10)]
 

# Question 4: Find all matches where Mexico is playing, 
# specifically as team1, AND the venue is "Estadio Azteca"
df[(df["team1"] == "Mexico") & (df["venue"] == "Estadio Azteca")]

# Question 5: Write the code to find all matches played in either "Toronto" OR "Vancouver"
df[(df["city"] == "Toronto") | (df["city"] == "Vancouver")].shape



# Question 6: Write a single line of pandas code to find matches where:
# team1 is ranked strictly better (lower number) than team2 AND
# The match is either in Mexico OR Canada

(9, 15)

## Aggregation

## Grouping